### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ganav** [oak-tree/springy#4]
hello 
my question is not related to this project but related to https://github.com/fchollet/keras/issues/6167
i am new with github so i do not know how to send u msg kk,,

How did you make keras print metrics as follows?
top_k_categorical_accuracy: 0.9303 - in_top2: 0.9279 - in_top3: 0.9279 - in_top4: 0.9303 - in_top5: 0.9303 - in_top7: 0.9303 - in_top10: 0.9303

I am new with keras i need to plot rank (top-1, top-2,....top-n) as you did as above.
can you please share me your code..

**Comment by oak-tree** [comment]
Hey @ganav I answered you at `keras` repo. I'm  closing this `issue`.

**Comment by oak-tree** [comment]
Hey @ganav I answered you at `keras` repo. I'm  closing this `issue`.
